--- #YAML:1.0
name:               Yandex-Tools
version:            0.13
abstract:           useful functions for Yandex daemons and programs.
author:
    - Petya Kohts <petya@kohts.ru>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Cwd:             0
    Schedule::Cron:  0
    Storable:        0
    Time::HiRes:     0
    Time::Local:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
