--- #YAML:1.0
name:               Yandex-Tools
version:            0.10
abstract:           useful functions for Yandex daemons and programs.
author:
    - Petya Kohts <kohts@yandex-team.ru>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Cwd:                  0
    Schedule::Cron::Events:  0
    Storable:             0
    Time::HiRes:          0
    Time::Local:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
